env:
  RUBY_VERSION: 3.0.2
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  DATABASE_USER: postgres
  DATABASE_PASSWORD: password

name: Rails tests
on: [push, pull_request]

jobs:
  rspec-test:
    name: RSpec
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U ${{ env.POSTGRES_USER }}"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=10

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true  # installs the Bundler your lockfile expects

      # ⬇️ Old Webpacker path needs Node 16 + Yarn 1.22.x
      - name: Use Node 16.x
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install Yarn 1.22.x
        run: npm i -g yarn@1.22.22

      - name: Install JS dependencies
        run: yarn install --frozen-lockfile

      - name: Install Postgres client headers
        run: sudo apt-get update && sudo apt-get install -y libpq-dev

      - name: Sanity check versions
        run: |
          ruby -v
          which ruby
          bundle -v
          which bundle
          node -v
          yarn -v

      - name: Create & migrate test DB
        env:
          RAILS_ENV: test
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate

      - name: Run tests
        run: bundle exec rspec .

      - name: Run brakeman
        run: bundle exec brakeman -o brakeman.txt || true

      - name: Run rubocop
        run: bundle exec rubocop --force-exclusion vendor/*/** --out rubocop.txt

      - name: Upload coverage results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: coverage

      - name: Upload rubocop report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: rubocop.txt
          path: rubocop.txt

      - name: Upload brakeman report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: brakeman.txt
          path: brakeman.txt
